// <auto-generated />
using System;
using DataServicio;
using Microsoft.Data.SqlTypes;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataServicio.Migrations
{
    [DbContext(typeof(FerreteriaDbContext))]
    [Migration("20260820035235_mejorasCampos")]
    partial class mejorasCampos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataServicio.Tabla.DireccionTbl", b =>
                {
                    b.Property<int>("DireccionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DireccionId"));

                    b.Property<string>("Calle")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Depto")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Numero")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("PersonaId")
                        .HasColumnType("int");

                    b.Property<string>("Piso")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("DireccionId");

                    b.HasIndex("PersonaId");

                    b.ToTable("Direccion");
                });

            modelBuilder.Entity("DataServicio.Tabla.EmailTbl", b =>
                {
                    b.Property<int>("EmailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmailId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(90)
                        .HasColumnType("nvarchar(90)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<int>("PersonaId")
                        .HasColumnType("int");

                    b.HasKey("EmailId");

                    b.HasIndex("PersonaId");

                    b.ToTable("Email");
                });

            modelBuilder.Entity("DataServicio.Tabla.LisPreProConfiguracionTbl", b =>
                {
                    b.Property<int>("LisPreProConfiguracionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LisPreProConfiguracionId"));

                    b.Property<string>("ClaveLocal")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("ClaveProveedor")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int?>("ListaPrecioProveedorId")
                        .HasColumnType("int");

                    b.HasKey("LisPreProConfiguracionId");

                    b.HasIndex("ListaPrecioProveedorId");

                    b.ToTable("LisPreProConfiguracion");
                });

            modelBuilder.Entity("DataServicio.Tabla.LisPreProDataTbl", b =>
                {
                    b.Property<int>("LisPreProDataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LisPreProDataId"));

                    b.Property<string>("Descripcion1")
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("Descripcion2")
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("Descripcion3")
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("Descripcion4")
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("Descripcion5")
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("Descripcion6")
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("LineaCruda")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ListaPrecioProveedorId")
                        .HasColumnType("int");

                    b.Property<double>("Valor1")
                        .HasColumnType("float");

                    b.Property<double>("Valor2")
                        .HasColumnType("float");

                    b.Property<double>("Valor3")
                        .HasColumnType("float");

                    b.HasKey("LisPreProDataId");

                    b.HasIndex("ListaPrecioProveedorId");

                    b.ToTable("LisPreProData");
                });

            modelBuilder.Entity("DataServicio.Tabla.ListaPrecioProveedorTbl", b =>
                {
                    b.Property<int>("ListaPrecioProveedorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ListaPrecioProveedorId"));

                    b.Property<string>("Comentario")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("FecIngreso")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreArchivo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NombreArchivoOriginal")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ProveedorId")
                        .HasColumnType("int");

                    b.HasKey("ListaPrecioProveedorId");

                    b.HasIndex("ProveedorId");

                    b.ToTable("ListaPrecioProveedor");
                });

            modelBuilder.Entity("DataServicio.Tabla.PersonaTbl", b =>
                {
                    b.Property<int>("PersonaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonaId"));

                    b.Property<string>("ApeMaterno")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("ApePaterno")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("CUIT")
                        .HasMaxLength(19)
                        .HasColumnType("nvarchar(19)");

                    b.Property<string>("DNI")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("PersonaId");

                    b.ToTable("Persona");
                });

            modelBuilder.Entity("DataServicio.Tabla.ProductoTbl", b =>
                {
                    b.Property<int>("ProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductoId"));

                    b.Property<string>("AtributosJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Codigo")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RubroA")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RubroB")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RubroC")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SinonimosJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TextoVectorial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<SqlVector<float>?>("VectorEmbedding")
                        .HasColumnType("vector(1536)");

                    b.HasKey("ProductoId");

                    b.ToTable("Producto");
                });

            modelBuilder.Entity("DataServicio.Tabla.ProveedorTbl", b =>
                {
                    b.Property<int>("ProveedorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProveedorId"));

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonaId")
                        .HasColumnType("int");

                    b.HasKey("ProveedorId");

                    b.HasIndex("PersonaId");

                    b.ToTable("Proveedor");
                });

            modelBuilder.Entity("DataServicio.Tabla.RubroFerreteriaTbl", b =>
                {
                    b.Property<int>("RubroFerreteriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RubroFerreteriaId"));

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RubroFerreteriaId");

                    b.ToTable("RubroFerreteria");
                });

            modelBuilder.Entity("DataServicio.Tabla.TelefonoTbl", b =>
                {
                    b.Property<int>("TelefonoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TelefonoId"));

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<int>("PersonaId")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("TelefonoId");

                    b.HasIndex("PersonaId");

                    b.ToTable("Telefono");
                });

            modelBuilder.Entity("DataServicio.Tabla.UsuarioTbl", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("LoginPwd")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("LoginUser")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("PersonaId")
                        .HasColumnType("int");

                    b.HasKey("UsuarioId");

                    b.HasIndex("PersonaId");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("ProveedorTblRubroFerreteriaTbl", b =>
                {
                    b.Property<int>("ProveedoresProveedorId")
                        .HasColumnType("int");

                    b.Property<int>("RubrosRubroFerreteriaId")
                        .HasColumnType("int");

                    b.HasKey("ProveedoresProveedorId", "RubrosRubroFerreteriaId");

                    b.HasIndex("RubrosRubroFerreteriaId");

                    b.ToTable("RubroFerreteriaRelacion", (string)null);
                });

            modelBuilder.Entity("DataServicio.Tabla.DireccionTbl", b =>
                {
                    b.HasOne("DataServicio.Tabla.PersonaTbl", "Persona")
                        .WithMany("Direcciones")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("DataServicio.Tabla.EmailTbl", b =>
                {
                    b.HasOne("DataServicio.Tabla.PersonaTbl", "Persona")
                        .WithMany("Emails")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("DataServicio.Tabla.LisPreProConfiguracionTbl", b =>
                {
                    b.HasOne("DataServicio.Tabla.ListaPrecioProveedorTbl", "ListaPrecioProveedor")
                        .WithMany("LisPreProConfiguracion")
                        .HasForeignKey("ListaPrecioProveedorId");

                    b.Navigation("ListaPrecioProveedor");
                });

            modelBuilder.Entity("DataServicio.Tabla.LisPreProDataTbl", b =>
                {
                    b.HasOne("DataServicio.Tabla.ListaPrecioProveedorTbl", "ListaPrecioProveedor")
                        .WithMany("LisPreProData")
                        .HasForeignKey("ListaPrecioProveedorId");

                    b.Navigation("ListaPrecioProveedor");
                });

            modelBuilder.Entity("DataServicio.Tabla.ListaPrecioProveedorTbl", b =>
                {
                    b.HasOne("DataServicio.Tabla.ProveedorTbl", "Proveedor")
                        .WithMany()
                        .HasForeignKey("ProveedorId");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("DataServicio.Tabla.ProveedorTbl", b =>
                {
                    b.HasOne("DataServicio.Tabla.PersonaTbl", "Persona")
                        .WithMany()
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("DataServicio.Tabla.TelefonoTbl", b =>
                {
                    b.HasOne("DataServicio.Tabla.PersonaTbl", "Persona")
                        .WithMany("Telefonos")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("DataServicio.Tabla.UsuarioTbl", b =>
                {
                    b.HasOne("DataServicio.Tabla.PersonaTbl", "Persona")
                        .WithMany()
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("ProveedorTblRubroFerreteriaTbl", b =>
                {
                    b.HasOne("DataServicio.Tabla.ProveedorTbl", null)
                        .WithMany()
                        .HasForeignKey("ProveedoresProveedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataServicio.Tabla.RubroFerreteriaTbl", null)
                        .WithMany()
                        .HasForeignKey("RubrosRubroFerreteriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataServicio.Tabla.ListaPrecioProveedorTbl", b =>
                {
                    b.Navigation("LisPreProConfiguracion");

                    b.Navigation("LisPreProData");
                });

            modelBuilder.Entity("DataServicio.Tabla.PersonaTbl", b =>
                {
                    b.Navigation("Direcciones");

                    b.Navigation("Emails");

                    b.Navigation("Telefonos");
                });
#pragma warning restore 612, 618
        }
    }
}
